### ISSUE TITLE
Sign up with metadata fails giving 403

### ISSUE THREAD

**Issue by ozexpert** [nolanlawson/pouchdb-authentication#101]
Hi, thanks for your awesome work. 

Just one problem reporting.. 
Having metadata fails to sign up. 
```
db.signup('robin', 'dickgrayson', {
  metadata : {
    email : 'robin@boywonder.com',
    birthday : '1932-03-27T00:00:00.000Z',
    likes : ['acrobatics', 'short pants', 'sidekickin\''],
  }
}, function (err, response) {
  // etc. 
});
```
and giving result of 
```
{"status":403,"name":"forbidden","message":"Forbidden by design doc validate_doc_update function","error":true,"reason":"Doc ID must be of the form org.couchdb.user:name"}
```

without metadata works fine. 
```
db.signup('robin', 'dickgrayson', function (err, response) {
  // etc. 
});
```

**Comment by ozexpert** [comment]
im using 0.5.1

**Comment by ozexpert** [comment]
ahhh. nevermind. it works.. 

i had `name` inside metadata and seems it conflicts with the username field. Maybe update the doc to NOT use `name` field for metadata. Thanks.

**Comment by runia1** [comment]
@ozexpert DUDE!  Thank you, that was the problem for me too!

**Comment by ozexpert** [comment]
Danke @runia1 DUDE! :-)
