### ISSUE TITLE
Build as UMD

### ISSUE THREAD

**Issue by nolanlawson** [nolanlawson/pouchdb-authentication#103]
Forgot to do `browserify --standalone` in the build process, hence `dist/pouchdb.authentication.js` isn't UMD.

**Comment by nolanlawson** [comment]
published as 0.5.2

**Comment by montogeek** [comment]
@nolanlawson Why not add it to the npm hooks?, so, you will never forget :D

**Comment by nolanlawson** [comment]
need to check the build assets into Git in order to make Bower happy; another reason I'll be happy to drop Bower support at some point :)
