### ISSUE TITLE
Change Password?  Lost Password?

### ISSUE THREAD

**Issue by MichaelJCole** [nolanlawson/pouchdb-authentication#11]
Hi, I'm still figuring this out.  I'm trying to build and off-line Chrome App.  https://developer.chrome.com/apps/about_apps

I plan to:
- Make a local PouchDB, 
- Sync it to a server CouchDB, 
- Use pouchdb-authentication
- Have user login with a password (to protect casual messing with their data)

How do I change a user's password?  And does that sync back to the server?

How do I reset the user's password if they lose it?

Thanks!

**Comment by ozexpert** [comment]
How? changePassword only works if user is logged in.
Seems even with server admin, this doesn't work giving 404 due to not passing the auth header.
