### ISSUE TITLE
Wkwebview not allowing cookie, then??

### ISSUE THREAD

**Issue by ozexpert** [nolanlawson/pouchdb-authentication#117]
Hi, this is related to cordova apps (especially ios - with wkwebview).
https://github.com/driftyco/cordova-plugin-wkwebview-engine/issues/23

Cookie is not enabled, so calling getSession() or getUser() won't work after login. 
Is there any other way to store rather than browser cookie?

Thanks a bunch.

**Comment by nolanlawson** [comment]
pouchdb-authentication uses CouchDB authentication, which is fundamentally based on cookies. There is no alternative login mechanism, no.

**Comment by ozexpert** [comment]
Expected, but yeah.. apparently this needs to get fixed in wkwebview. Thanks! 👍

**Comment by gkiko** [comment]
@ozexpert How did you deal with the problem? Switched back to UIWebView?

**Comment by ozexpert** [comment]
@gkiko unfortunately, i moved away from cordova and no longer using webview.
