### ISSUE TITLE
Integration with hello.js

### ISSUE THREAD

**Issue by arnoutaertgeerts** [nolanlawson/pouchdb-authentication#12]
Would it be possible to integrate this plugin with [hello.js](http://adodson.com/hello.js/)?
Hello.js allows you to login to an external service (such as google/facebook/...).

The plugin works like this:

```javascript
hello("google").login.then(function() {
   //Is it possible to securely login a user here using pouchdb-authentication?
})
```

Or would this be impossible cause of security reasons?

**Comment by jspenc72** [comment]
Nolan you are correct, behavior is automatic.
