### ISSUE TITLE
Import pouchdb-authentication

### ISSUE THREAD

**Issue by glaucocustodio** [nolanlawson/pouchdb-authentication#125]
Hi, I am using this library (`^0.5.5`) with Ionic 2 beta and now I am migrating to rc1.

In Ionic 2 beta I had this code working:
```javascript
var PouchDB = require("pouchdb");
PouchDB.plugin(require('pouchdb-authentication'));
```
Now in rc1 I have this:
```javascript
import PouchDB from 'pouchdb';
const remoteDB = new PouchDB(remoteDbHost)
```

How can I import and use this plugin now?

Thanks.

**Comment by hadrien-toma** [comment]
In an Ionic 2 RC0 project, I tried the following code :
`import Pouchdb from 'pouchdb'`
`import PouchdbAuthentication from 'pouchdb-authentication'`
`Pouchdb.plugin(PouchdbAuthentication)`

I have a build success but the browser fails by giving this error :
`request.js:3 : Uncaught ReferenceError: require is not defined(…)`

Any idea of what is going on?

**Comment by nolanlawson** [comment]
Ionic 2 is moving from Rollup to Webpack which should fix this issue.
