### ISSUE TITLE
How to get session cookie after login

### ISSUE THREAD

**Issue by ozexpert** [nolanlawson/pouchdb-authentication#138]
Hi, I'm trying to implement social login with PouchDB. Unfortunately, pouchDB/CoucbDB doesn't provide an easy way to do social login, i'm trying to do it this way. 

- From my NodeJS server, implement login with PouchDB and get session cookie return to the client (as response). 
- My client code will store the cookie session returned by the NodeJS server and use that to automatically login.

Now, I want to know whether how i can get the session cookie after using pouchdb's login() function. Since the interaction is done in server-side (not in the browser), i need to get the session cookie in some way. 

Any advise or help? Thank you. PouchDB is awesome!

**Comment by nolanlawson** [comment]
You might want to look at [superlogin](https://www.npmjs.com/package/superlogin) instead; pouchdb-authentication is just a thin layer on top of CouchDB's built-in authentication. Hope that helps!
