### ISSUE TITLE
Offline first and Pouch Auth integration together?

### ISSUE THREAD

**Issue by mikeulkeul** [nolanlawson/pouchdb-authentication#15]
Hello,
I like what you have done with PouchDB, being able to create an app with such an easy api to store all the data is great. Pouch is offline first and it's really great to develop with.

The only way I succeed in making this plugin to work was using this code : 

```
var db1 = new PouchDB("http://localhost:5984/test_db")
db1.getSession().then(function(x)){console.log(x)}
db1.getUser('myUser').then(function(x)){console.log(x)}
```

It works but I don't have the offline first features I was expected. Is there any way this pouchDB plugin can be use to get the authentication and offline first features working together?
Something that could look like this code ?

```
var db1 = new PouchDB('db1')
PouchDB.sync('http://localhost:5984/db1', 'db1');
db1.getSession().then(function(x)){console.log(x)}
db1.getUser('myUser').then(function(x)){console.log(x)}
```

I feel quite stuck with this issues as those two features are important to me. Creating a user document in my main database seems a bad solution.

Any suggestion would be super appreciated.

**Comment by brachycera** [comment]
Is this still the recommended way to implement offline first users?
