### ISSUE TITLE
Login not returning username for admin

### ISSUE THREAD

**Issue by echo66** [nolanlawson/pouchdb-authentication#16]
Greetings!

I noticed that, for my admin user, when I login through PouchDB (using this plugin), the "name" field is undefined. But, for other users, it's present.

{
  "ok": true,
 "name":null,
 "roles":["_admin"]
}"

I'm using the last release (0.3.6), as far as I know.

**Comment by nolanlawson** [comment]
Closing, reopen if needed. :)

**Comment by michaeljosephrosenthal** [comment]
from what I can tell, this is an issue when authenticating from node environments. An existing user will have their name in `getSession` and `login`'s responses from the browser, but not from the server
