### ISSUE TITLE
Why force http/https ?

### ISSUE THREAD

**Issue by simonaberry** [nolanlawson/pouchdb-authentication#20]
I was wondering why the plugin forces you to authenticate against an online couchdb ? 

My app uses a local pouchdb that syncs to Iriscouch - the main reason being that the local db is available when the user is offline (it's inside a Chrome App ... 'Offline First').

What if  a user wanted to login to his offline app when there was no internet connection ?

**Comment by nolanlawson** [comment]
This plugin is designed to show you what CouchDB authentication can do, which by definition is online. :)

For offline authentication, I would be very interested to see an implementation of that, and it has been discussed before, but this plugin is not concerned with that. You'd need to write another plugin probably.

Alternatively, you can check yourself whether or not the user if online, and then choose whether or not to sync based on that. Lemme know if that helps.

**Comment by simonaberry** [comment]
Thanks
