### ISSUE TITLE
src folder

### ISSUE THREAD

**Issue by cosmi** [nolanlawson/pouchdb-authentication#21]
Is it possible to publish src folder?
Or am I missing something?

**Comment by nickcolley** [comment]
The entry point is lib/index.js https://github.com/nolanlawson/pouchdb-authentication/blob/master/package.json#L5

**Comment by cosmi** [comment]
Okay, I'll check that. I keep getting errors like:
`Error: Cannot find module './timeout' from '/Users/cosmi/projects/chess/bower_components/pouchdb-authentication/dist` from the dist .js

**Comment by cosmi** [comment]
ok, seems I was using it from bower and bower.json doesn't list all dependencies (incorrectly?)

**Comment by nolanlawson** [comment]
Actually the entry point for the browser script is `dist/pouchdb.authentication.js`. And I list it as [the "main" script for Bower](https://github.com/nolanlawson/pouchdb-authentication/blob/460d339948fb19633f9a0ed0a9f78db9912a4d2d/bower.json#L5), so I'm surprised Bower isn't picking it up.

**Comment by nolanlawson** [comment]
Closing this, and yeah, Bower doesn't install all your dependencies for you and will probably be deprecated in favor of npm some day.
