### ISSUE TITLE
Cloudant

### ISSUE THREAD

**Issue by ronag** [nolanlawson/pouchdb-authentication#22]
When trying to login with Cloudant I get the following error: 
```
const remoteDB = new PouchDB('https://foo123.cloudant.com/mydb')
remoteDB.login('fender', 'test123', function(err, response) {
  console.log(err, response)
})
```
```
{message: "you must specify application/x-www-form-urlencoded as the primary content-type", status: 400, name: "bad_request"
```

Creating users worked fine.

Here are the ajax options:
```
{
    "method": "POST",
    "url": "https://foo123.cloudant.com:/_session",
    "body": {
        "name": "fender",
        "password": "test123"
    }
}
```

**Comment by ronag** [comment]
I've almost gotten it to work, see https://github.com/BoffinsDev/pouchdb-authentication/commit/19691654f4457bc74f861dcd1c0b8fcde887dec5

However, I had to change the login request from `POST` to `GET` and therefore I don't get the auth cookie back. Any ideas?

**Comment by ronag** [comment]
Ok. Now I'm getting successful answers for not signUp and login.

However, the following doesn't work:

```javascript
const remoteDB = new PouchDB('https://ronag.cloudant.com/templates')

remoteDB.login('test', 'qwe123', function(err, response) {
  console.log('login', err, response)
  remoteDB.post({title: 'test'}, function(err, response) {
    console.log('post', err, response)
  })
})
```

First of all I get up a dialog in chrome where it asks for username and password. When I press cancel the post fails. However, the login succeeds. What's going on?

**Comment by ronag** [comment]
It seems I have 2 problems:

1. The authentication required dialog pops up before I get a chance to log in.
2. The Auth cookie doesn't seem to be set for some reason. Even though I can see in Chrome dev tools that it is received. But when looking in the resources tab there is nothing there.

**Comment by willholley** [comment]
Have you enabled CouchDB style auth on Cloudant (see the bottom of https://cloudant.com/for-developers/faq/auth/)? Out of the box, Cloudant uses its own auth layer - you have to bypass it to use CouchDB auth.

**Comment by nolanlawson** [comment]
Closing because this is not designed to work in Cloudant.

**Comment by srsgores** [comment]
Having the same problem on my end.  At first, I tried setting ``dataType: "application/x-www-form-urlencoded"``, but after that failed, I tried disabiling the cloudant authentication layer:

```
{
  "couchdb_auth_only": true
}
```

I had no idea what the author of the cloudant documentation meant with all their roles:

```
{
  "couchdb_auth_only": true,
  "members": {
    "names": ["demo"],"roles":[]
  },
  "admins": {...}
}
```

What is supposed to replace the ``{...}``?  If it's an array, shouldn't the format be: ``"admins": []``?

I'm still lost on this, so I would appreciate any advice from @ronag on how he bypassed this authentication layer.

**Comment by willholley** [comment]
the format of the _security object when bypassing Cloudant auth is the same as CouchDB (see http://docs.couchdb.org/en/latest/intro/security.html#authorization). You will have to manually create a _users database and populate it with the appropriate user documents (same as CouchDB). Note that Cloudant today matches an older CouchDB security API where the user passwords have to be hashed on the client side (see http://stackoverflow.com/questions/18039704/cloudant-auth-lacks-users-database and http://wiki.apache.org/couchdb/Security_Features_Overview).

In the next few months we're going to have much stronger alignment between Cloudant and CouchDB 2.0, at which point I'd expect server-side password hashing to be supported.

**Comment by tohagan** [comment]
@willholley Does setting "couchdb_auth_only": true affect any other aspects of the Cloudant API?

Can we safely sync Cloudant _user objects with SHA1 hashing to a CouchDb 1.6.1 service?

**Comment by willholley** [comment]
@tohagan I'm not aware of any functionality besides auth that will be affected. In terms of syncing Cloudant _user objects to CouchDB 1.6.1, that's not something I've seen before but I'd guess that if it works CouchDB -> CouchDB, it will work Cloudant -> CouchDB if CouchDB is configured to use SHA1 rather than pbkdf2 (which is the default) for password hashing.

**Comment by tohagan** [comment]
Ok thanks. That's what I figured. At least I know you're not aware of any issues.

**Comment by tohagan** [comment]
@willholley I have one more question ... Do I need to add a _security object to the _users database?  

For other databases if you don't configure a _security object then you grant everyone access to everyone - so double checking that Cloudant does not do this for _user !

**Comment by willholley** [comment]
@tohagan unless you specify otherwise, the _users database will have use Cloudant's security layer. If you override it, using couchdb_auth_only, then CouchDB rules apply. For instance, you could create a Cloudant API Key and grant it read/write access to the _users database and have other databases use CouchDB-style security.
