### ISSUE TITLE
Change Password

### ISSUE THREAD

**Issue by jo** [nolanlawson/pouchdb-authentication#26]
It would be nice to have functionality built in to change a password, eg:

```js
db.changePassword()
```
Its basically just a get `_user`, set `doc.password` and `put` the doc back nowadays (since CouchDB 1.2).

Would you accept a pull request for that?

**Comment by nolanlawson** [comment]
Sure, I like it. :+1:

**Comment by nolanlawson** [comment]
fixed in https://github.com/nolanlawson/pouchdb-authentication/pull/27/commits
