### ISSUE TITLE
Cannot get document after login

### ISSUE THREAD

**Issue by yesir1006** [nolanlawson/pouchdb-authentication#30]
Hi,
I am working with pouchdb-authentication in one db per user mode and set up couchdb followed your doc. I come across a problem when I first loading page, I get a 401 error when use db.get after login successful, but if I refresh page, it all works fine. I don't know why, here is my code and log.

```js
pouchService.userdb.allDocs({
                    include_docs: true,
                    attachments: true
                }).then(function(doc) {
                    console.log('[home]: ' + username + ' login ' + 'user');
                    pouchService.clientdb = new PouchDB(host + username);
                    return pouchService.clientdb.login(username, password).then(function() {
                        //log in client db
                        console.log('[home]: ' + username + ' login ' + username);
                        console.log('[home]: ' + 'fetching project list');
                        return pouchService.clientdb.get('doc');
                    })
                }).then(function(doc) {
                    //fetch project list
                    console.log('[home]: ' + 'project list fetched');
                    ...
```

```
[home]: yy login user
app.js:287 [home]: logging in yy
172.16.11.223:5984/yy/?_nonce=1431499152129:1 GET http://172.16.11.223:5984/yy/?_nonce=1431499152129 401 (Unauthorized)
app.js:291 [home]: yy login yy
app.js:292 [home]: fetching project list
app.js:333 [home]: {"status":401,"name":"unauthorized","message":"Name or password is incorrect."}
Resource interpreted as Image but transferred with MIME type text/plain: "blob:http%3A//localhost%3A8100/10940aae-8e34-4e24-876e-e80a66bd3f39".
```

![2015-05-13 2 39 25](https://cloud.githubusercontent.com/assets/10625618/7605297/609da3a8-f980-11e4-9008-eb8b87371831.png)

Any idea on how to solve this? 
Thanks for your help!

**Comment by nolanlawson** [comment]
Protip: you can get JavaScript syntax highlighting by adding:

    ```js
    your javascript goes here
    ```

I added it for you. :)

Anyway, it looks like the error is that you need to log in before you try to do anything. (401 means unauthenticated.) You can accomplish this by doing:

```js
var db = new PouchDB('http://whatever', {auth: {username: 'username', password: 'password'}})
```

**Comment by yesir1006** [comment]
Thanks, but it doesn't work.:( I know it is authentication issue and I do login db using username and password in 
```js
return pouchService.clientdb.login(username, password).then(function() {
```
I thought it would do authentication for me. The problem seems that it goes into then function of login but actually it did not authenticate for me. And what is weird is that I always happened when I first load page, if I refresh the page all works fine. Any idea on this? Thanks!

**Comment by nolanlawson** [comment]
On some setups you may need to log in using the PouchDB constructor as well as using `login()`. Not really sure what's going on here, but glad it's working. :)
