### ISSUE TITLE
How does the login work? 

### ISSUE THREAD

**Issue by danielo515** [nolanlawson/pouchdb-authentication#32]
Hello, 

I'm curious how login method works. How does it keep the session? Or maybe it just sets te cookie and leave the rest to pouch? 

Thank you!

**Comment by nolanlawson** [comment]
There are some details in the CouchDB guide: http://guide.couchdb.org/draft/security.html#cookies

**Comment by nolanlawson** [comment]
Let me know if that answers your question. :)

**Comment by danielo515** [comment]
Hello @nolanlawson 

That explains how couch cookie authentication works. Thanks for that, but that does not gives me any clue about how the library manages login. Will the library keep the cookie internally and use it? Or it's something the browser does automatically? (sorry for my lack of knowledge about this). What happens when the cookie expires? Does the library ask for another one by itself or should I do another login again? 

Thanks for your answer.

**Comment by nolanlawson** [comment]
This library does not handle the cookies at all. It merely wraps some CouchDB HTTP APIs to make them more convenient. :)

**Comment by danielo515** [comment]
Hello @nolanlawson ,

That is what I was guessing, that there is no much difference between this library and plain http requests.

Thank you very much for confirming. And thank you very much for the awesome piece of work Pouch is.

Regards
