### ISSUE TITLE
login() throwing illegal_database_name error for '_session'

### ISSUE THREAD

**Issue by RichardLitt** [nolanlawson/pouchdb-authentication#39]
When I try to use the `login()` method, I am getting an `illegal_database_name` error for `_session`. I'm guessing this has something to do with `utils.getSessionUrl`, which is returning `http://54.164.xxx.xxx:xxxx///_session` (anonymized). Here is the complete error:

```js
{ [illegal_database_name: Database encountered an unknown error]
  status: 400,
  name: 'illegal_database_name',
  message: 'Database encountered an unknown error',
  error: true,
  reason: 'Name: \'_session\'. Only lowercase characters (a-z), digits (0-9), and any of the characters _, $, (, ), +, -, and / are allowed. Must begin with a letter.' }
```

I don't see why this is being thrown. ~~Half of the time, I am also getting an `{ [Error: read ECONNRESET] status: 400 }`, but I'm guessing that is just my connection.~~ Any ideas?

**Comment by jbenet** [comment]
the `///` implies to me that some parameters arent being written. looks like a missing db name

**Comment by RichardLitt** [comment]
That works for `_user`, though. I thought I had the solution solved when I included:

```js
        var ajaxOpts = {
          ajax: {
            headers: {
              Authorization: 'Basic ' + btoa(user.name + ':' + password)
            }
          }
        }
```

According to this spec http://docs.couchdb.org/en/1.6.1/api/server/authn.html?highlight=session#delete--_session I should be able to POST to _session, so I don't know why it is throwing an `illegal_database_name`.

**Comment by RichardLitt** [comment]
The reference code is here: https://github.com/RichardLitt/beagle-heroku/blob/master/auth.js#L95-L148. To run, run `$ node test.js -r signup` and then `$ node test.js -r login`. Some env vars may need to be set.

**Comment by RichardLitt** [comment]
That seems to be the error, @jbenet. More specifically, these lines in lib/utils.js:

```
function getBaseUrl(db) {
  // console.log('db.getUrl()', db.getUrl(), db.getUrl().replace(/\/[^\/]+\/?$/, ''))
  return db.getUrl().replace(/\/[^\/]+\/?$/, '');
}
```
The console log illustrates the error: `$` isn't working as an end of line regex marker, for me. What I ended up doing was adding on `/_session` and then replacing `///` with `/`, which worked.  

Any idea what this is isn't working as expected?

**Comment by jbenet** [comment]
no idea. maybe try `/\/[^\/]+\/?$/m` ? (multiline? this is a stab in the dark)

**Comment by ronyrun** [comment]
@nolanlawson it works :)

**Comment by dasois** [comment]
I also have this problem, how do we get this done? I'm happy to help!

**Comment by nolanlawson** [comment]
@dasois there was some progress in this PR (https://github.com/nolanlawson/pouchdb-authentication/pull/74), but I would feel most comfortable if we had a new test to go along with the change.

**Comment by staxmanade** [comment]
Hey @nolanlawson, 
I tried to debug this a little - let me know if this helps. I was looking to send a PR to this repo - but it looks like it may potentially be a `pouchdb` issue instead?

In the following function:  [`function genUrl(opts, path)` ](https://github.com/pouchdb/pouchdb/blob/4c25b549089651472e391227e591f20e72745704/src/adapters/http/index.js#L115) 

in the case the last line: `'/' + opts.path + pathDel + path;` with the given input I tested with on localhost resolves to the following values `"/" + "" + "" + "/"`.

So with the following `opts` value: (with a `path === "/"`)

```json
{
  "anchor": "",
  "query": "",
  "file": "",
  "directory": "/",
  "path": "",
  "relative": "/",
  "port": "5984",
  "host": "localhost",
  "password": "",
  "user": "",
  "userInfo": "",
  "authority": "localhost:5984",
  "protocol": "http",
  "source": "http://localhost:5984/",
  "queryKey": {},
  "db": ""
}
```

gives the extra `//`

I don't know if the [`function genUrl(opts, path)` ](https://github.com/pouchdb/pouchdb/blob/4c25b549089651472e391227e591f20e72745704/src/adapters/http/index.js#L115) or [`getDBUrl`](https://github.com/pouchdb/pouchdb/blob/4c25b549089651472e391227e591f20e72745704/src/adapters/http/index.js#L102) shouldn't be passing in `/` for the path in this case?

Thoughts?

**Comment by nolanlawson** [comment]
@staxmanade It looks like PouchDB's ajax module is not correctly joining paths, yes. However I'd rather fix it in the plugin rather than in PouchDB, since it's quicker to update this plugin and publish than wait for a new PouchDB release. I agree though that it should probably be fixed in both places ultimately.

**Comment by nolanlawson** [comment]
fixed by https://github.com/nolanlawson/pouchdb-authentication/pull/93. I'll release a new version today

**Comment by staxmanade** [comment]
👍 💥  ✅

**Comment by nolanlawson** [comment]
v0.5.1, thanks for fixing this after such a long wait!

**Comment by RichardLitt** [comment]
Woo!
