### ISSUE TITLE
Usage with PouchDB only (no CouchDB)

### ISSUE THREAD

**Issue by bguiz** [nolanlawson/pouchdb-authentication#46]
Sample app uses PouchDB on both the client and the server, by using `express`, `pouchdb` and `express-pouchdb` on the server:

https://github.com/bguiz/pouchdb-express-demo/blob/develop/server/index.js#L3-L5

Now in this project, one of the stated requirements is "CouchDB v1.3.0+ or IrisCouch" for the server. Which features of CouchDB that aren't present in PouchDB are necessary? How feasible is it to use the `pouchdb-authentication` on a set up with PouchDB on the server?

**Comment by nolanlawson** [comment]
I'm not 100% sure, but I believe this plugin should work with PouchDB Server as well, since PouchDB Server implements most of the CouchDB 1.x APIs. You can try it and let us know! :)

**Comment by bguiz** [comment]
@nolanlawson Yeah, so I just tried it out, and it seems to work just
fine... almost

I quickly realised that the following error message means that I could
not interact with the local DB (which is replaicated to the remote
DB), and instead have to interact with the remote one directly:

> This plugin only works for the http/https adapter. So you should use new PouchDB("http://mysite.com:5984/mydb") instead.

Which makes sense, after all, the remote DB should be the one that
gets to determine auth stuff.

However, after switching over, I get this error, which was not there before:


```
Uncaught (in promise) TypeError: Uncaught, unspecified "error" event.
    at TypeError (native)
    at r.27.n.emit
(http://localhost:8099/js/3rd/pouchdb/pouchdb-3.0.6.min.js:9:28320)
    at http://localhost:8099/js/3rd/pouchdb/pouchdb-3.0.6.min.js:9:18379
```

I feel that it is most likely unrelated, so closing this ticket. Let
me know if this rings any bells though!
W: http://bguiz.com
