### ISSUE TITLE
From mongod to pouchdb/couchdb

### ISSUE THREAD

**Issue by agozie** [nolanlawson/pouchdb-authentication#48]
I want to migrate my app from mongodb to pouchdb/couchdb for the syncing. But I am lost. My app has 20 collections in a mongo database. One collection holds the users, who can only view content they created in the other collections, using their ids. I implemented my own user management system. Now, with 'one database per user', do i have to create 19 databases for each user or put everything into one database?

**Comment by nolanlawson** [comment]
It's really hard to give specific advice; everybody's case is different. But if you really prefer to think in terms of "collections" and/or "relationships," then you may enjoy relational-pouch: https://github.com/nolanlawson/relational-pouch

**Comment by agozie** [comment]
After reading "tons" of documentation on pouchdb.com, especially http://pouchdb.com/2014/05/01/secondary-indexes-have-landed-in-pouchdb.html, and some head scratching, I've started porting to pouchdb/couchdb! I'm loving it, just had to start thinking differently. Thanks for the awesomeness.

**Comment by nickcolley** [comment]
@agozie that's great to hear! If you've got any more questions feel free to open another issue up, thanks for using PouchDB! :+1:
