### ISSUE TITLE
Missing final semicolon in dist file

### ISSUE THREAD

**Issue by saturnlevrai** [nolanlawson/pouchdb-authentication#53]
It missing semicolon at final line of pouchdb.authentication.js dist file. That create troubles when use grunt concat. Please add this missing semicolon.
Thank you.
Best regard,
Antoine Michéa.

---
UPDATE :
Anyway i self resolve by using grunt conf :
 concat: {
            options: {
              separator: ';',
            }
        }

**Comment by nickcolley** [comment]
Awesome, glad you sorted it @saturnlevrai

https://github.com/gruntjs/grunt-contrib-concat#separator for any future travellers that need this.
