### ISSUE TITLE
authentication is lost when user document is updated

### ISSUE THREAD

**Issue by arnoutaertgeerts** [nolanlawson/pouchdb-authentication#6]
Is it possible a user loses authentication after they perform an update of their own document?

I think this is what is happening in my application:

1. User <test> logs in with his credentials.
2. He updates his own email address stored in his user document. (org.couchdb.user:test)
3. He looses authentication. (?)

Why does this last step happen and is it possible to prevent this from happening? Or do I need to create a new database with the additional user-info aside from roles, paswords etc?

**Comment by nolanlawson** [comment]
Please provide a test to reproduce and reopen as necessary.
