### ISSUE TITLE
Shouldn't pouchdb be a peerDependency?

### ISSUE THREAD

**Issue by nnarhinen** [nolanlawson/pouchdb-authentication#60]
..or at least upgraded to 5.x?

**Comment by nickcolley** [comment]
Yo @nnarhinen !

Since this repo uses the CouchDB (and PouchDB server) backend authentication it's probably sound for you to use 5.x and it'll work fine.

I wonder if we could get greenkeeper running on here @nolanlawson ?

Failing that you could popover a PR if you wanted in the meantime.

**Comment by nolanlawson** [comment]
The parts of PouchDB that are used by this plugin are just `ajax`, which basically means that I am using it as a lightweight shim for `jQuery.ajax`.

So no, it doesn't need PouchDB to be a peerDep.

**Comment by nnarhinen** [comment]
Yeah, but this does mean that I get extra bits to my client-side bundles, doesn't it? Because at least `npm ls` lists now two pouchdbs..

**Comment by nolanlawson** [comment]
Yes, there is a minimal amount of overhead. I just measured it, and it's about 8.2KB.

Pull requests are welcome. I don't really understand how peerDeps work, TBQH.
