### ISSUE TITLE
[feature request] db.putUser for updating user metadata

### ISSUE THREAD

**Issue by mattmarcum** [nolanlawson/pouchdb-authentication#64]
We have the `db.getUser` method and we can create metadata with the `db.signup` method but there doesn't appear to be a way to update the user doc after its created.  I think there'd be a lot of overlap with the `signup` method.

**Comment by nolanlawson** [comment]
In fact `signup` is basically the same thing as `putUser`, at least from CouchDB's perspective. Closing this issue for now.

**Comment by jgillich** [comment]
The issue with `signup` is that it requires you to provide a password. I'll submit a PR for this.

**Comment by jgillich** [comment]
#89
