### ISSUE TITLE
Credentential in plain text ? Is there a way to avoid that ?

### ISSUE THREAD

**Issue by Razgort** [nolanlawson/pouchdb-authentication#65]
Hi,

I'm beginning to work with pouchDB and couchDB, and i'm trying to use your plugin in my app. But there is something that bothers me when i do that : 
var user = {
  name: 'admin',
  password: 'admin'
};

var pouchOpts = {
  skipSetup: true
};

var ajaxOpts = {
  ajax: {
    headers: {
      Authorization: 'Basic ' + window.btoa(user.name + ':' + user.password)
    }
  }
};

var db = new PouchDB('http://localhost:5984/test', pouchOpts);

db.login(user.name, user.password, ajaxOpts).then(function() {
  return db.allDocs();
}).then(function(docs) {
  console.log(docs);
}).catch(function(error) {
  console.error(error);
});

The credentials are in plain text in the request and for me it's a major security issue. Is there a way to avoid that or am i doing it wrong ?

Thx in advance.

**Comment by nickcolley** [comment]
Hey @Razgort !

If your username and password is being supplied from the user (might be you in this case) you can encrypt it on the client and reuse it so it's not in the code base. Then if you pass it to your server via HTTPS it should be secure.

To achieve this you could:
- Remove the username and password from the application.
- Ask for the username and password from the user at runtime
- Encrypt the username and password locally (could use something like https://github.com/calvinmetcalf/crypto-pouch)
- Use HTTPS for traffic

Hopefully this helps.

**Comment by Razgort** [comment]
So there is no HTTP digest support ?

**Comment by nolanlawson** [comment]
Right, the only solution to the "credentials in plaintext" problem is HTTPS. And no, Pouch/Couch do not support OAuth, sorry about that.

Furthermore, cookie authentication is usually better than basic authentication; there is some info about that here: http://guide.couchdb.org/draft/security.html
