### ISSUE TITLE
preflight problem

### ISSUE THREAD

**Issue by ramstein74** [nolanlawson/pouchdb-authentication#68]
when testing your code ( i replaced localhost by my laptop lan ip. I created a db called test and set admin password as admin )
![image](https://cloud.githubusercontent.com/assets/1210858/12302230/187cf0a8-ba1c-11e5-8af7-d9e5265ed999.png)
i get this error
![image](https://cloud.githubusercontent.com/assets/1210858/12302190/d9543562-ba1b-11e5-8183-2066a833ea18.png)
having this in couchdb
![image](https://cloud.githubusercontent.com/assets/1210858/12302200/ec4a2ffa-ba1b-11e5-902a-2e9520f4e8a1.png)

![image](https://cloud.githubusercontent.com/assets/1210858/12302215/fcd49194-ba1b-11e5-89df-3e443946392d.png)

Can you point where the problem is ?

thank you

**Comment by nolanlawson** [comment]
It looks like you're missing some of the CORS header settings. You can correct that by using: https://github.com/pouchdb/add-cors-to-couchdb
