### ISSUE TITLE
Creating a user with roles

### ISSUE THREAD

**Issue by redgeoff** [nolanlawson/pouchdb-authentication#76]
Assume the default design docs for the users database. Let's say I have an admin user with username `myuser` and password `mypassword`. When I execute:

```js
var db = new PouchDB('http://myuser:mypassword@localhost:5984/mydb');

db.signup('batman', 'brucewayne', { roles: 'myrole' }, function (err, response) {
  if (err) {
    console.log('err=', err);
  }
});
```

I get the error:
```js
{ [forbidden: Forbidden by design doc validate_doc_update function]
  status: 403,
  name: 'forbidden',
  message: 'Forbidden by design doc validate_doc_update function',
  error: true,
  reason: 'Only _admin may set roles' }
```

I can issue the following via curl and it works just fine:
```js
curl -HContent-Type:application/json -vXPUT myuser:mypassword@localhost:5984/_users/org.couchdb.user:batman --data-binary '{"_id": "org.couchdb.user:batman","name": "batman","roles": ["myrole"],"type": "user","brucewayne": "mypassword"}'
```

I just wanted to make sure that I'm not doing something wrong before I start poking around more at the pouchdb and pouchdb-authentication code.

**Comment by redgeoff** [comment]
Interesting, the issue only appears to occur when running this code in node--it works fine in the browser. I'm investigating...

**Comment by redgeoff** [comment]
For now, I sidestepped this problem by using [nano](https://github.com/dscape/nano) instead. I think there may be a bug somewhere in pouchdb/pouchdb-authentication.

**Comment by nolanlawson** [comment]
Yes, pouchdb-authentication does not really work properly in Node, although that hasn't stopped people from trying. ;)

**Comment by dbandstra** [comment]
I'm having this problem in the browser.

Actually the only reason I was able to add users at all (without roles) was that I didn't have any user/role settings in the _users database's security object (so I guess any old guest was free to add users). Now that I've added restrictions on the security object, I can't do anything on the _users database from my web app.

I think it has something to do with CORS. The preflight OPTIONS for the PUT doesn't include 'authorization' in Access-Control-Request-Headers, and so the PUT never includes any auth information. The preflight only requests 'accept' and 'content-type'.

I do have CORS set up in my CouchDB config and didn't have any issues with PouchDB in general until this.

**Comment by delkant** [comment]
Same problem in the browser(Chrome) here too . 
This is my env.:  PouchDB 5.4.4, pouchdb-authentication v0.5.1, CouchDB 1.6.1.

Is this fixed? why the issue is closed? Where can I get more info on how to create default roles for new users if this is not the way to do it?  Thanks a lot!.

**Comment by Kluskey** [comment]
@delkant @nolanlawson Also having this issue when calling db.getUser() for a user that's already logged in. Any thoughts?
