### ISSUE TITLE
getSession() not working in Electron

### ISSUE THREAD

**Issue by nylki** [nolanlawson/pouchdb-authentication#78]
I am trying to authenticate a user in the rendering context of [Electron](http://electron.atom.io/), not the node context.
I am able to `login()`, however any `getSession()` afterwards only gets a `name: null`.

Electron has an event handler method [app.login](https://github.com/atom/electron/blob/master/docs/api/app.md#event-login), however this is never triggered when trying PouchDB stuff.

I suppose it has something to do with cookie handling inside Electron? Is there anything I could test or try out instead? (I know I could use *nano* in the node context, but that would add too much overhead for my application)

**Comment by nolanlawson** [comment]
My guess is that Electron is trying to run this module in a Node context rather than a browser context. Maybe just including a script tag instead of `require('pouchdb-authentication')` will work?

**Comment by nylki** [comment]
@nolanlawson thank you, that's it! :dancers: 

I actually had `pouchdb` itself inside a regular script tag, but unfortunately not `pouchdb-authentication` I did `PouchDB.plugin(require('pouchdb-authentication'))` instead of 
using a script tag.

For future reference, if anybody wants to quickly try out the main features of *pouchdb-authentication*, I created a quick'n'dirty repo for this purpose:
https://github.com/nylki/pouchdb-authentication-electron-test
