### ISSUE TITLE
Absolute path in build

### ISSUE THREAD

**Issue by 2i** [nolanlawson/pouchdb-authentication#79]
From https://github.com/nolanlawson/pouchdb-authentication/blob/v0.4.3/dist/pouchdb.authentication.js#L286:

    }).call(this,require("/Users/nolan/workspace/pouchdb-authentication/node_modules/process/browser.js"))
    },{"./uuid":3,"/Users/nolan/workspace/pouchdb-authentication/node_modules/process/browser.js":13,"inherits":5,"pouchdb-extend":8,"pouchdb/extras/ajax":9,"pouchdb/extras/promise":10}],3:[function(require,module,exports){

Both lines contain the ominous path `/Users/nolan/workspace/pouchdb-authentication/node_modules/process/browser.js`. For most users this points to nirvana.

**Comment by 2i** [comment]
If I compile it on my machine, I get the following:

[pouchdb.authentication.js.zip](https://github.com/nolanlawson/pouchdb-authentication/files/169982/pouchdb.authentication.js.zip)

with 

    }).call(this,require('_process'))
    },{"./uuid":4,"_process":1,"inherits":6,"pouchdb-extend":9,"pouchdb/extras/ajax":10,"pouchdb/extras/promise":11}],4:[function(require,module,exports){

on line 439.

No `browser.js` is `require`-d.

**Comment by nolanlawson** [comment]
This is due to an old version of Browserify. It's completely harmless, although it is annoying.
