### ISSUE TITLE
'denied' error during sync if user's session has expired

### ISSUE THREAD

**Issue by Anyante** [nolanlawson/pouchdb-authentication#82]
Hi all

My scenario is similar to the Twitter example ("Everybody can read, only some can write (some things").
I've created a validate_doc_update function (remote DB) to enforce that users only can modify their own documents.

Everything is working smoothly now - as long as the user is logged in / online (e.g. the auth cookie exists).

Unfortunately, I'm not sure how to handle the offline / session expired scenario correctly.
A user is able to save a doc (to the local DB) even if he's offline/not logged in (auth cookie expired).

As soon as the browser is online again, the remote DB returns a 'denied' error for that document. This is correct at that moment because the user is not logged in (auth cookie expired).
However, the document never gets pushed to the remote DB.

How should I handle this? "retry" a (full?) replication after the user has logged in again?
Handle the 'denied' event somehow?

Regards,
Anyante

**Comment by nolanlawson** [comment]
Probably in those cases you should just retry a full replication again. Either that or you should verify that the user is logged in before replicating. Sorry I don't have a better answer for this; the CouchDB folks (e.g. #couchdb on IRC Freenode) may be able to provide better advice.

**Comment by nolanlawson** [comment]
Also FWIW keep in mind that this repo is basically just a thin layer over CouchDB authentication, so really in case of weird situations like cookie expiration and `denied` events, I'm mostly beholden to core PouchDB and CouchDB. Undoubtedly there are improvements that can be made to CouchDB's authentication system, but the best place to take those suggestions would be CouchDB itself.

**Comment by Anyante** [comment]
Thanks for your answers.
I kind of fixed my issue for now. Here is what I did if anyone is interested:

- I'm storing the username (localStorage) to use it while in offline mode
- I've separated the "push" replication (to the remote DB) from the "pull" replication
- The "push" replication uses a filter function to only push docs of the current/logged in username
- As soon as I get a 'denied' error I assume the session has expired and "logout" the user locally
- After a sucessful login I start a full "push" replication (since: 0) for the current user (filter function). This way earlier 'denied' docs get pushed again to to remote DB.

I'm not sure if this is the right way to do it, but it's working.
There might be performance issues during this "full push" after a successful login... I dunno.

If someone has a better idea please let me know.

**Comment by alejandro-heredia-coderoad-com** [comment]
Using pouchdb-authentication on an Ionic 1.3.2 hybrid application. I get a similar error when the device is on **standby** until session expires. Then when the devices **resumes** I handle a re-authentication.
