### ISSUE TITLE
getSession only functional AFTER a timeout...?

### ISSUE THREAD

**Issue by oodavid** [nolanlawson/pouchdb-authentication#83]
I've been somewhat baffled by sessions today.

In my browser console I can happily signup() and login() and getSession() shows me the current user.
If I refresh and just do getSession() in the console, I can see I still have the same user.

BUT. The moment I move my logic to a script file in the <head> of my page, getSession() never shows the expected user:

```
var remote = new PouchDB('http://localhost:5984/app', { skipSetup: true });
remote.getSession()
.then(function(response){
    console.log(response);
    if(!response.userCtx || !response.userCtx.name || response.userCtx.name != couchUser){
        console.log('Nope');
    } else {
        console.log('Yep: '+response.userCtx.name);
    }
});
```
However, if I move that logic into a setTimeout, it works as expected:
```
var remote = new PouchDB('http://localhost:5984/app', { skipSetup: true });
setTimeout(function(){
    remote.getSession()
    .then(function(response){
        console.log(response);
        if(!response.userCtx || !response.userCtx.name || response.userCtx.name != couchUser){
            console.log('Nope');
        } else {
            console.log('Yep: '+response.userCtx.name);
        }
    });
}, 100); // Times as low as 10ms worked.
```
Is there a preferred place to run the code? IE: document.onload?

**Comment by nolanlawson** [comment]
This sounds like a bug. Not sure exactly why it happens, though, but it may be related to `skipSetup`.

**Comment by oodavid** [comment]
That's good to know re skipSetup.

I'm no longer seeing the error as I've moved my logic into an Angular controller that's triggered "onload". Seems consistent but I'll keep an eye on it - I hope it doesn't bite me in the arse later!

**Comment by nolanlawson** [comment]
Thanks! Please reopen as necessary.
