### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by dasois** [nolanlawson/pouchdb-authentication#87]
It would be great to have TypeScript definition files for this...

**Comment by nolanlawson** [comment]
I believe TypeScript definitions usually go in a separate repo from the source project? Although I could be wrong.

In any case, I'd be happy to see someone write TS defs for this project. :)

**Comment by dasois** [comment]
(http://www.typescriptlang.org/docs/handbook/typings-for-npm-packages.html)

**Comment by nolanlawson** [comment]
I think I would prefer to put the Typescript definitions in DefinitelyTyped. There are already some definitions for PouchDB itself over here: http://definitelytyped.org/

Thanks for opening the issue, though, and if you'd like to contribute the TypeScript definitions to DefinitelyTyped, that would be awesome. :)

**Comment by dasois** [comment]
TypeScript definitions describe the structure of the code, so they have to be versioned and maintained with the code. PouchDB definitions already are outdated...

**Comment by nolanlawson** [comment]
You're right; I saw that those definitions were out of date. 😦 OTOH, I don't think it's necessarily the responsibility of JS module authors to maintain every possible way of consuming their library (e.g. TypeScript, CoffeeScript, ES6 modules, etc.). So for that reason, I really like DefinitelyTyped's approach of keeping the definitions in a separate repo. Hopefully someone with more interest/investment in TypeScript will go in and update the definitions…
