### ISSUE TITLE
username and password are not encoded

### ISSUE THREAD

**Issue by garth** [nolanlawson/pouchdb-authentication#88]
If the username or password contain meaningful url chars then it breaks (eg &,+,...)

These values should be encoded here https://github.com/nolanlawson/pouchdb-authentication/blob/master/lib/index.js#L86

**Comment by SinanGabel** [comment]
See also this important Mozilla note on encoding and decoding:

https://developer.mozilla.org/en-US/docs/Web/API/WindowBase64/Base64_encoding_and_decoding#The_Unicode_Problem

**Comment by nolanlawson** [comment]
https://github.com/nolanlawson/pouchdb-authentication/pull/90
