### ISSUE TITLE
Safari 7 don't allows third-party cookies by default and login doesn't persist

### ISSUE THREAD

**Issue by brandomeniconi** [nolanlawson/pouchdb-authentication#9]
Hi,

I've developed an app under Chrome that runs on a domain and queries a CouchDb hosted at couchappy.com and works good but when I tested it in Safari the login is successful but if I after call getSession, the response says that I'm not logged in. 

I've finally discovered that if I allow third party cookies in Safari settings, it works good.

how can i solve this problem?

Thanks

**Comment by nolanlawson** [comment]
This is a CouchDB/Safari issue, not an issue with this plugin, so closing.
