### ISSUE TITLE
Cloudant support finally!

### ISSUE THREAD

**Issue by luandro** [nolanlawson/pouchdb-authentication#92]
Since the [pouchdb-authentication-cloudant](https://github.com/willholley/pouchdb-authentication) doesn't have an issues page, I'd just like confirmation that Cloudant has finally added the support for hashing, and thus supports this plugin. I tested and it seems to be working fine, anyone else?

I added the cloudant fork to [npm](https://www.npmjs.com/package/pouchdb-authentication-cloudant), and would like to update with a BIG deprecation warning. We could also add a notice do the README, that Cloudant finally supports this.

**Comment by ronyrun** [comment]
Does this work properly for you ?
I can't create a user on my Cloudant side.

```nodejs
var PouchDB = require('pouchdb');
PouchDB.plugin(require('pouchdb-authentication'));

//with Admin account
var dbUrl =  encodeURI('https://Adminlogin:pwd@my-app.cloudant.com/MyDB');
var db = new PouchDB(dbUrl, {skipSetup: true});


var options = {
  metadata : {
    email : 'robin@boywonder.com',
    birthday : '1932-03-27T00:00:00.000Z',
    likes : ['acrobatics', 'short pants', 'sidekickin\''],
  }
};

console.log("go signup");
db.signup('batman', 'brucewayne', options)
  .then(function(response){
    console.log(response);
    return response;
  })
  .then(function(response){
    console.log("response",response);
    return db.login('superman', 'clarkkent');
  })
  .then(function(login){
    console.log("login",login);
  })
  .catch(function(err){
    if (err.name === 'conflict') {
      console.log("batmanalready exists, choose another username");
    } else if (err.name === 'forbidden') {
      console.log("invalid username");
    } else {
      console.log(err,"HTTP error, cosmic rays, etc.");
    }
  });
```

I get that : 

```
{ [unauthorized: Name or password is incorrect.]
  status: 401,
  name: 'unauthorized',
  message: 'Name or password is incorrect.',
  error: true,
  reason: '_writer access is required for this request' }
```

**Comment by nolanlawson** [comment]
That's great to hear! Please contact Cloudant support to help with these sorts of things. Else when everything is good to go, I'd be happy to accept a PR noting in the README that Cloudant support is now available.

**Comment by luandro** [comment]
I'm sorry. It appears to have been a bug. Cloudant is not yet supported.
