### ISSUE TITLE
Listening to user changes

### ISSUE THREAD

**Issue by jgillich** [nolanlawson/pouchdb-authentication#96]
I need to listen to changes to a user, in order to keep the metadata in sync. I haven't tried it yet, but it should be easily possible through polling the _changes feed with `doc_ids` set to the user document. @nolanlawson Do you think it would make sense to have this in pouchdb-authentication?

**Comment by nolanlawson** [comment]
I believe instead you can just `new PouchDB('http://localhost:5984/_users').changes()`, right? If we can avoid putting it in pouchdb-authentication, I would prefer, because I think the API has already gotten quite big, and that seems out-of-scope for simple authentication stuff.

**Comment by jgillich** [comment]
Sure that's fine with me, it's not much code anyway - like you said, it would just be a wrapper around `db.changes()` with `doc_ids` set to the user doc.
