### ISSUE TITLE
Allowing roles with putUser

### ISSUE THREAD

**Issue by kdoran** [nolanlawson/pouchdb-authentication#97]
https://github.com/nolanlawson/pouchdb-authentication/blob/master/lib/index.js#L28

Is there any reason not to allow editing roles with `putUser`? Something like:

 user = utils.extend(true, user, opts.metadata);
 user = utils.extend(true, user, opts.roles);

**Comment by nolanlawson** [comment]
Yes, you can do `{metadata: roles: ['foo', 'bar']`}. The idea is that user information goes in `metadata`.
