### ISSUE TITLE
db.login promise chaining

### ISSUE THREAD

**Issue by jeffleus** [nolanlawson/pouchdb-authentication#99]
First off, love the PouchDB work Nolan.  Way to go.  Your contribution to the OpenSource/JS community is much appreciated.  Second, my issue very well could be an issue w/ the way I setup my promise chaining and not the library.  But I am posting here since it is directly related to making my Pouch project work...

I would like to chain a login using your repo, to a local database setup, and remote sync.  I would also like to eventually insert a step to return an encryption key from the remote db upon login to allow decrypting the local db w/ crypto-pouch.  Anyway, I have an _init function as follows:

```
function _init() {
_login()
  .then( _setDatabase() )            
  .then( _startSync() )
  .then( _startListening() );
}
```
the login step is provided as follows:

```
function _login() {
  var userDb = new PouchDB(_remotedb, {skipSetup: true});
    return userDb.login('USERNAME', 'USERPWD')
      .catch(function(err) {
        return $q.reject(err);
      });
}
```
I have tried several combinations of catch statement, callbacks, $q.when and $q.reject in the _init() function as well as the _login() function.  No scenario seems to appropriate "short-circuit" the _init promise chain and stop.  I would like a failed pwd error to stop the proceedings and deal accordingly.  But the .then steps all proceed before the catch.  What am I doing wrong?

-Jeff

**Comment by jeffleus** [comment]
Uggh!  It WAS my code.  No surprise.  I messed up by including the parenthesis in the subsequent ".then()" statements the functions were being evaluated.  Instead I should be providing the function reference w/out the parenthesis to allow the promise to decide on execution.  Not sure of the correct terminology in all this.  But thought I should include a comment for anyone else interested.  My new code is as follows:
```
function _init() {
_login()
  .then( _setDatabase )            
  .then( _startSync )
  .then( _startListening )
  .catch( function(e) {
    console.error(e);
    if (e.name === 'unauthorized') {
      'do something if authentication failed on login
    }
  });
}
```
And the corresponding functions look like
```
function _login() {
    var userDb = new PouchDB(_remotedb, {skipSetup: true});
    return userDb.login('admin', 'Eraser$15');
}
function _setDatabase() {
    _database = new PouchDB(_localdb);
    self.database = _database;
    return $q.when( _database );
}
etc...
```
Now, if the login fails authentication, the chain of promises "short-circuits" to the catch handler and I can stop the db sync proceedings.

**Comment by nolanlawson** [comment]
Yup, that is definitely the error. It's a common mistake when you using promises!

By the way, I wrote a blog post on promises that details this error as well as other common errors; you might enjoy it: https://pouchdb.com/2015/05/18/we-have-a-problem-with-promises.html
